services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d    # db初期化
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    restart: always

  front:
    build: ./front
    volumes:
      - ./front/app:/app
    ports:
      - 3000:3000
    depends_on:
      - back
    restart: always
  
  back:
    build: ./back
    volumes:
      - ./back/app:/app
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

volumes:
  db_data: